### ISSUE TITLE
imgly-sdk 1.0 (rewrite) roadmap

### ISSUE THREAD

**Issue by saschagehlich** [imgly/imgly-sdk-html5#11]
I'm currently working on a rewrite of the JavaScript SDK. It will be written in **pure JavaScript**, will have an **extensive documentation**, an **easy-to-use API** which will allow you to easily modify and extend the SDK, and it will also be **entirely test-driven** (aiming for 100% code coverage).

You can take a look at the current state by switching to the [rewrite branch](https://github.com/imgly/imgly-sdk-html5/tree/rewrite). Please note that this is **highly work-in-progress**, so please don't create any issues as long as it's not released.

Here's the roadmap:

* Basic architecture
  * [X] Specify the API to modify and extend the SDK
  * [X] Implement operations stack rendering
  * [X] Image dimensions calculation
* Rendering
  * [x] Basic image rendering (Canvas2D)
  * [X] Final image resizing (Canvas2D)
  * [x] Basic image rendering (WebGL)
  * [x] Final image resizing (WebGL)
* Operations
  * [x] Canvas2D
  * [x] WebGL
* User Interface
  * [x] Basic UI architecture
  * Default UI
    * [x] Image / canvas rendering
    * [x] Zoom
    * [x] Operations
      * [x] Filters
      * [x] Rotation
      * [x] Cropping
        * [x] Canvas controls
        * [x] Custom ratios
        * [x] Select ratios
      * [x] Brightness
      * [x] Contrast
      * [x] Saturation
      * [x] Flip
      * [x] Radial Blur
      * [x] Tilt/Shift Blur
      * [x] Text
      * [x] Stickers
      * [x] Frames
* Tutorials
  * Will follow...

**Comment by RacZo** [comment]
Hi awesome job @saschagehlich!,

Does this rewrite consumes less memory than the original sdk?

Please let me know if I can help with the rewrite's development.

**Comment by saschagehlich** [comment]
Hey @RacZo,

I just wanted to reply to your original comment in #8, but I'll reply here instead. This rewrite supports both WebGL and the normal 2D canvas on both desktop and mobile. For 2D canvas, we will not be able to reduce the memory usage, but with WebGL the SDK will consume way less memory, as the image is being processed on the GPU.

This rewrite will also has full touch support built-in. We will hopefully start a beta by mid-february.

Thanks :)
